# Site settings
title: "Jiangshan Mu | Ph.D. | he/him/his | Postdoctoral Fellow | Atmospheric Chemistry and Air Pollution"
tagline: "Atmospheric Chemistry • Air Pollution • Inequality"
email: mujiangshan0615@gmail.com
description: > # used for SEO/meta
  Research on atmospheric chemistry and air pollution.
  Global NO2 dataset (2005–2023), exposure and inequality analyses.

# GitHub Pages URLs
# Your repo is jiangshanmu/mujsh.github.io → project site
url: "https://jiangshanmu.github.io"
baseurl: ""

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

sass:
  style: :compressed

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
